# Skills data

mapping = {
    "Luck": "luck",
    "Sanity": "sanity",

    "STR": "str",
    "DEX": "dex",
    "INT": "int",
    "APP": "app",
    "POW": "pow",
    "SIZ": "siz",
    "EDU": "edu",

    "Accounting" : "accounting",
    "Anthropology" : "anthropology",
    "Appraise" : "appraise",
    "Archaeology" : "archaeology",
    "Art/Craft" : "art_craft",
    "Charm" : "charm",
    "Climb" : "climb",
    "Credit Rating" : "credit_rating",
    "Cthulhu Mythos" : "cthulhu_mythos",
    "Disguise" : "disguise",
    "Dodge" : "dodge",
    "Drive Auto" : "drive_auto",
    "Elec. Repair" : "elec_repair",
    "Fast Talk" : "fast_talk",
    "Fighting (Brawl)" : "fighting_brawl",
    "Firearms (Handguns)" : "firearms_handguns",
    "Firearms (Rifle/Shotguns)" : "firearms_rifle_shotguns",
    "Firearms (Lightning Gun)" : "firearms_lightning_gun",
    "First Aid" : "first_aid",
    "History" : "history",
    "Intimidate" : "intimidate",
    "Jump" : "jump",
    "Language (Own)" : "language_own",
    "Law" : "law",
    "Library Use" : "library_use",
    "Listen" : "listen",
    "Locksmith" : "locksmith",
    "Mech. Repair" : "mech_repair",
    "Medicine" : "medicine",
    "Natural World" : "natural_world",
    "Navigate" : "navigate",
    "Occult" : "occult",
    "Op. Hv. Machine" : "op_hv_machine",
    "Persuade" : "persuade",
    "Pilot" : "pilot",
    "Psychology" : "psychology",
    "Psychoanalysis" : "psychoanalysis",
    "Ride" : "ride",
    "Science" : "science",
    "Sleight of Hand" : "sleight_of_hand",
    "Spot Hidden" : "spot_hidden",
    "Stealth" : "stealth",
    "Survival" : "survival",
    "Swim" : "swim",
    "Throw" : "throw",
    "Track" : "track",
}
